### ISSUE TITLE
More examples in the documentation

### ISSUE THREAD

**Issue by kaname-png** [DevYukine/Kurasuta#397]
Actually, I still don't understand how to use this package with Discord-Akairo, I don't see examples, Could you provide more more practical examples when it comes to frameworks?

The problem I have right now is that when starting for example, 3 clusters, with 1 shard in each one, the bot responds to me 3 times, I don't understand

I would very much like to use this package, but I have no examples to understand its use

**Comment by ZTzTopia** [comment]
yes i dont understand too :(

**Comment by inhydrox** [comment]
> Actually, I still don't understand how to use this package with Discord-Akairo, I don't see examples, Could you provide more more practical examples when it comes to frameworks?
> 
> The problem I have right now is that when starting for example, 3 clusters, with 1 shard in each one, the bot responds to me 3 times, I don't understand
> 
> I would very much like to use this package, but I have no examples to understand its use

You could set `clusterCount: 1`

**Comment by kaname-png** [comment]
@inhydrox that is not a solution to the problem since if I want to have more clusters I will have the problem again

**Comment by DevYukine** [comment]
Hey! Thanks for your interest in better Documentation, i fully agree that it would be nice to have better examples & docs but i sadly currently do not have time to work on this library beside doing bugfixes (i would also like to rewrite it not using Veza anymore since that causes a lot of issues). I will put a "Help Wanted" label in case anybody wants to help and making a pr with documentation but for the next time i think it will not be possible for me to do so myself.

**Comment by inhydrox** [comment]
> @inhydrox that is not a solution to the problem since if I want to have more clusters I will have the problem again

So you can leave clusters undefined and it will take like if your CPU is 1 core it will 1 cluster if it's 2 it will take 2 clusters
